IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Products'))
	BEGIN
		CREATE TABLE Products
		(
			ProductId BIGINT NOT NULL IDENTITY(1,1),
			ProductGuid UNIQUEIDENTIFIER NOT NULL,
			Name VARCHAR(100) NOT NULL,
			Description VARCHAR(500) NULL,
			Value DECIMAL(12,2) NOT NULL,
			Quantity INT NOT NULL,
			IsActive BIT NOT NULL,
			CreatedAt DATETIME NOT NULL,
			CONSTRAINT PK_Products PRIMARY KEY NONCLUSTERED (ProductId, ProductGuid)
		)
	END