IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Customers'))
	BEGIN
		CREATE TABLE Customers
		(
			CustomerId BIGINT NOT NULL IDENTITY(1,1),
			CustomerGuid UNIQUEIDENTIFIER NOT NULL,
			Name VARCHAR(100) NOT NULL,
			Email VARCHAR(100) NOT NULL,
			NationalId VARCHAR(11) NOT NULL,
			IsActive BIT NOT NULL,
			CreatedAt DATETIME NOT NULL,
			-- PK
			CONSTRAINT PK_Customers PRIMARY KEY NONCLUSTERED (CustomerId, CustomerGuid)
		)
	END